version: "3.7"
services:
  server1:
    container_name: random_holiday_service1
    image: inaamiii/random_holiday_service1
    build: ./service1
    ports: 
    - published: 5000
      target: 5000
        
  server2:
    container_name: service_2_api
    image: inaamiii/service_2_api
    build: ./service2
    

  server3:
    container_name: service_3_api
    image: inaamiii/service_3_api
    build: ./service3
        

  server4:
    container_name: service_4_api
    image: inaamiii/service_4_api
    build: ./service4

    
 