version: "3.8"
services:
    server1:
        container_name: random_holiday_service1
        image: inaamiii/random_holiday_service1
        build: ./service1
        ports: 
        - published: 5000
          target: 5000
        
    server2:
        container_name: random_holiday_service2
        image: inaamiii/random_holiday_service2
        build: ./service2
        ports: 
            - published: 5001
              target: 5001


    server3:
        container_name: random_holiday_service3
        image: inaamiii/random_holiday_service3
        build: ./service3
        ports: 
            - published: 5002
              target: 5002
    

    server4:
        container_name: random_holiday_service4
        image: inaamiii/random_holiday_service4
        build: ./service4
        ports: 
            - published: 5003
              target: 5003
     
 