
- name: Install Docker Dependencies 
  apt:
    pkg:
    - apt-get install 
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg 
    - lsb-release
    update_cache: True
- name: Add Docker GPG Key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 
- name: Add Docker APT Repository 
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename| lower }} stable
    state: present 
- name: Install Docker Engine 
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli 
    - ca-certificates 
    - containerd.io
    update_cache: True
- name: Add Ubunutu User to Docker group 
  ansible.builtin.user:
    name: ubuntu 
    groups: docker 
    append: yes 
- name: Start Docker Service
  service: 
    name: docker
    state: started
- name: pip docker
  pip: 
    executable: pip3 
    name: docker 
- name: Add users to docker group  #change user to jenkins when using jenkins 
  user: Inaam
  groups: docker 
  append: True




